#1(x² with intermediate layers from test2 with dropout). Hidden param= 1.648 million
encoded = Dense(units=794, activation='relu')(input_img)
encoded = Dropout(0.8)(encoded)
encoded = Dense(units=628, activation='relu')(encoded)
encoded = Dropout(0.6)(encoded)
encoded = Dense(units=461, activation='relu')(encoded)
encoded = Dropout(0.5)(encoded)
encoded = Dense(units=321, activation='relu')(encoded)
encoded = Dropout(0.5)(encoded)
encoded = Dense(units=180, activation='relu')(encoded)
encoded = Dropout(0.2)(encoded)
encoded = Dense(units=113, activation='relu')(encoded)
encoded = Dropout(0.2)(encoded)
encoded = Dense(units=45, activation='relu')(encoded)
encoded = Dense(units=37, activation='relu')(encoded)
encoded = Dropout(0.2)(encoded)
encoded = Dense(units=29, activation='relu')(encoded)
encoded = Dense(units=16, activation='relu')(encoded)
encoded = Dense(units=bottle_dim, activation='linear')(encoded)

decoded = Dense(units=29, activation='relu')(encoded)
decoded = Dense(units=45, activation='relu')(decoded)
decoded = Dense(units=180, activation='relu')(decoded)
decoded = Dense(units=461, activation='relu')(decoded)
decoded = Dense(units=794, activation='relu')(decoded)

#2(x² removed layers from test2 with dropout). Hidden param=0.772 million
encoded = Dense(units=794, activation='relu')(input_img)
encoded = Dropout(0.5)(encoded)
encoded = Dense(units=180, activation='relu')(encoded)
encoded = Dropout(0.2)(encoded)
encoded = Dense(units=29, activation='relu')(encoded)
encoded = Dense(units=bottle_dim, activation='linear')(encoded)

decoded = Dense(units=29, activation='relu')(encoded)
decoded = Dense(units=45, activation='relu')(decoded)
decoded = Dense(units=180, activation='relu')(decoded)
decoded = Dense(units=461, activation='relu')(decoded)
decoded = Dense(units=794, activation='relu')(decoded)

#3(x² with filter layer from test2 with dropout): Hidden param= 3.831 million
encoded = Dense(units=3000, activation='relu')(input_img)
encoded = Dropout(0.8)(encoded)
encoded = Dense(units=461, activation='relu')(encoded)
encoded = Dropout(0.5)(encoded)
encoded = Dense(units=180, activation='relu')(encoded)
encoded = Dropout(0.5)(encoded)
encoded = Dense(units=45, activation='relu')(encoded)
encoded = Dropout(0.2)(encoded)
encoded = Dense(units=29, activation='relu')(encoded)
encoded = Dense(units=bottle_dim, activation='linear')(encoded)

decoded = Dense(units=29, activation='relu')(encoded)
decoded = Dense(units=45, activation='relu')(decoded)
decoded = Dense(units=180, activation='relu')(decoded)
decoded = Dense(units=461, activation='relu')(decoded)
decoded = Dense(units=794, activation='relu')(decoded)